### ISSUE TITLE
Clipper doesnt read the CSGO installation folder

### ISSUE THREAD

**Issue by seythegamer** [f0e/clipper#1]
[0] Failed to load config, saving default
[0] C:\Users\PC\Desktop\clipper-main\clipper\src\index.ts:24
[0]     startServer(config.ports.server);
[0]                                                          ^
[0] Error: CSGO folder does not exist
[0]     at C:\Users\PC\Desktop\clipper-main\clipper\src\index.ts:21:9
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (C:\Users\PC\Desktop\clipper-main\clipper\src\index.ts:24:58)

**Comment by seythegamer** [comment]
Ill just post whole console log:
C:\Users\PC\Desktop\clipper-main>yarn start
yarn run v1.22.17
$ concurrently "yarn start-clipper" "yarn start-manager"
$ cd manager && yarn start
$ cd clipper && yarn start
$ craco start
$ ts-node .
[1] (node:748) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\PC\Desktop\clipper-main\manager\node_modules\postcss-safe-parser\node_modules\postcss\package.json.
[1] Update this package.json to use a subpath pattern like "./*".
[1] (Use `node --trace-deprecation ...` to show where the warning was created)
[0] Failed to load config, saving default
[0] C:\Users\PC\Desktop\clipper-main\clipper\src\index.ts:24
[0]     startServer(config.ports.server);
[0]                                                          ^
[0] Error: CSGO folder does not exist
[0]     at C:\Users\PC\Desktop\clipper-main\clipper\src\index.ts:21:9
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (C:\Users\PC\Desktop\clipper-main\clipper\src\index.ts:24:58)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
[0] yarn start-clipper exited with code 1
[1] i ｢wds｣: Project is running at http://192.168.0.45/
[1] i ｢wds｣: webpack output is served from
[1] i ｢wds｣: Content not from webpack is served from C:\Users\PC\Desktop\clipper-main\manager\public
[1] i ｢wds｣: 404s will fallback to /
[1] Starting the development server...
[1]
[1] Browserslist: caniuse-lite is outdated. Please run:
[1] npx browserslist@latest --update-db
[1]
[1] Why you should do it regularly:
[1] https://github.com/browserslist/browserslist#browsers-data-updating
[1] Compiled with warnings.
[1]
[1] src\components\MapIcon\MapIcon.tsx
[1]   Line 35:5:  React Hook useEffect has a missing dependency: 'setIcon'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[1]   Line 37:9:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images   jsx-a11y/alt-text
[1]
[1] src\pages\Home\Home.tsx
[1]   Line 52:5:  React Hook useEffect has a missing dependency: 'getClips'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[1]
[1] src\pages\Settings\Settings.tsx
[1]   Line 69:5:  React Hook useEffect has a missing dependency: 'getConfig'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[1]
[1] Search for the keywords to learn more about each warning.
[1] To ignore, add // eslint-disable-next-line to the line before.
[1]
[1] Proxy error: Could not proxy request /get-demos from localhost:3000 to http://localhost:3001/.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
[1]

**Comment by f0e** [comment]
Thanks for letting me know, should be fixed in 95a0dd402d0d7357b200b91c6f7b3b8be3801fd4.
